// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: grades.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Grade_PostGrade_FullMethodName = "/client.Grade/PostGrade"
)

// GradeClient is the client API for Grade service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GradeClient interface {
	PostGrade(ctx context.Context, in *GradeRecord, opts ...grpc.CallOption) (*GradeResponse, error)
}

type gradeClient struct {
	cc grpc.ClientConnInterface
}

func NewGradeClient(cc grpc.ClientConnInterface) GradeClient {
	return &gradeClient{cc}
}

func (c *gradeClient) PostGrade(ctx context.Context, in *GradeRecord, opts ...grpc.CallOption) (*GradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GradeResponse)
	err := c.cc.Invoke(ctx, Grade_PostGrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GradeServer is the server API for Grade service.
// All implementations must embed UnimplementedGradeServer
// for forward compatibility.
type GradeServer interface {
	PostGrade(context.Context, *GradeRecord) (*GradeResponse, error)
	mustEmbedUnimplementedGradeServer()
}

// UnimplementedGradeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGradeServer struct{}

func (UnimplementedGradeServer) PostGrade(context.Context, *GradeRecord) (*GradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostGrade not implemented")
}
func (UnimplementedGradeServer) mustEmbedUnimplementedGradeServer() {}
func (UnimplementedGradeServer) testEmbeddedByValue()               {}

// UnsafeGradeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GradeServer will
// result in compilation errors.
type UnsafeGradeServer interface {
	mustEmbedUnimplementedGradeServer()
}

func RegisterGradeServer(s grpc.ServiceRegistrar, srv GradeServer) {
	// If the following call pancis, it indicates UnimplementedGradeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Grade_ServiceDesc, srv)
}

func _Grade_PostGrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GradeRecord)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GradeServer).PostGrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Grade_PostGrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GradeServer).PostGrade(ctx, req.(*GradeRecord))
	}
	return interceptor(ctx, in, info, handler)
}

// Grade_ServiceDesc is the grpc.ServiceDesc for Grade service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Grade_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "client.Grade",
	HandlerType: (*GradeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostGrade",
			Handler:    _Grade_PostGrade_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grades.proto",
}
