// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v5.29.2
// source: grades.proto

package client

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GradeRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Carnet        string                 `protobuf:"bytes,1,opt,name=carnet,proto3" json:"carnet,omitempty"`
	Nombre        string                 `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Curso         string                 `protobuf:"bytes,3,opt,name=curso,proto3" json:"curso,omitempty"`
	Nota          int32                  `protobuf:"varint,4,opt,name=nota,proto3" json:"nota,omitempty"`
	Semestre      string                 `protobuf:"bytes,5,opt,name=semestre,proto3" json:"semestre,omitempty"`
	Year          int32                  `protobuf:"varint,6,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GradeRecord) Reset() {
	*x = GradeRecord{}
	mi := &file_grades_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeRecord) ProtoMessage() {}

func (x *GradeRecord) ProtoReflect() protoreflect.Message {
	mi := &file_grades_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeRecord.ProtoReflect.Descriptor instead.
func (*GradeRecord) Descriptor() ([]byte, []int) {
	return file_grades_proto_rawDescGZIP(), []int{0}
}

func (x *GradeRecord) GetCarnet() string {
	if x != nil {
		return x.Carnet
	}
	return ""
}

func (x *GradeRecord) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *GradeRecord) GetCurso() string {
	if x != nil {
		return x.Curso
	}
	return ""
}

func (x *GradeRecord) GetNota() int32 {
	if x != nil {
		return x.Nota
	}
	return 0
}

func (x *GradeRecord) GetSemestre() string {
	if x != nil {
		return x.Semestre
	}
	return ""
}

func (x *GradeRecord) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type GradeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GradeResponse) Reset() {
	*x = GradeResponse{}
	mi := &file_grades_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeResponse) ProtoMessage() {}

func (x *GradeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grades_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeResponse.ProtoReflect.Descriptor instead.
func (*GradeResponse) Descriptor() ([]byte, []int) {
	return file_grades_proto_rawDescGZIP(), []int{1}
}

func (x *GradeResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

var File_grades_proto protoreflect.FileDescriptor

var file_grades_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x67, 0x72, 0x61, 0x64, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x22, 0x97, 0x01, 0x0a, 0x0b, 0x47, 0x72, 0x61, 0x64, 0x65,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x61, 0x72, 0x6e, 0x65, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x61, 0x72, 0x6e, 0x65, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x6f, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6e, 0x6f, 0x74, 0x61,
	0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6d, 0x65, 0x73, 0x74, 0x72, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6d, 0x65, 0x73, 0x74, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x79, 0x65, 0x61, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72,
	0x22, 0x2b, 0x0a, 0x0d, 0x47, 0x72, 0x61, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x40, 0x0a,
	0x05, 0x47, 0x72, 0x61, 0x64, 0x65, 0x12, 0x37, 0x0a, 0x09, 0x50, 0x6f, 0x73, 0x74, 0x47, 0x72,
	0x61, 0x64, 0x65, 0x12, 0x13, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x47, 0x72, 0x61,
	0x64, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x1a, 0x15, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x2e, 0x47, 0x72, 0x61, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_grades_proto_rawDescOnce sync.Once
	file_grades_proto_rawDescData = file_grades_proto_rawDesc
)

func file_grades_proto_rawDescGZIP() []byte {
	file_grades_proto_rawDescOnce.Do(func() {
		file_grades_proto_rawDescData = protoimpl.X.CompressGZIP(file_grades_proto_rawDescData)
	})
	return file_grades_proto_rawDescData
}

var file_grades_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grades_proto_goTypes = []any{
	(*GradeRecord)(nil),   // 0: client.GradeRecord
	(*GradeResponse)(nil), // 1: client.GradeResponse
}
var file_grades_proto_depIdxs = []int32{
	0, // 0: client.Grade.PostGrade:input_type -> client.GradeRecord
	1, // 1: client.Grade.PostGrade:output_type -> client.GradeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grades_proto_init() }
func file_grades_proto_init() {
	if File_grades_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grades_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grades_proto_goTypes,
		DependencyIndexes: file_grades_proto_depIdxs,
		MessageInfos:      file_grades_proto_msgTypes,
	}.Build()
	File_grades_proto = out.File
	file_grades_proto_rawDesc = nil
	file_grades_proto_goTypes = nil
	file_grades_proto_depIdxs = nil
}
