CREATE DATABASE IF NOT EXISTS monitor;
USE monitor;

CREATE TABLE IF NOT EXISTS vm (
	ip VARCHAR(20) PRIMARY KEY NOT NULL
);

CREATE TABLE IF NOT EXISTS cpu (
	id INT AUTO_INCREMENT PRIMARY KEY,
	time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	percentage_used FLOAT NOT NULL,
  	ip VARCHAR(20),
	FOREIGN KEY (ip) REFERENCES vm(ip)
);

CREATE TABLE IF NOT EXISTS process (
	id INT AUTO_INCREMENT PRIMARY KEY,
	pid FLOAT NOT NULL,
	name VARCHAR(50) NOT NULL,
	state VARCHAR(50) NOT NULL,
	puser VARCHAR(50) NOT NULL,
	ram FLOAT,
	father FLOAT,
  	ip VARCHAR(20),
	time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (ip) REFERENCES vm(ip)
);

CREATE TABLE IF NOT EXISTS ram (
	id INT AUTO_INCREMENT PRIMARY KEY,
	total_ram INT NOT NULL,
	free_ram INT NOT NULL,
	used_ram INT NOT NULL,
	percentage_used INT NOT NULL,
  	ip VARCHAR(20),
	time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (ip) REFERENCES vm(ip)
);