[package]
name = "redis_client"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
# serde_json = { version = "1.0.134" }
redis = { version = "0.27.6", features = ["async-std-comp", "json"] }